version: '3'
services:
  api:
    image: soqet/oxs-stats:api
    depends_on:
      - redis
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        folder: api
    environment:
      - PORT=${API_PORT}
      - DB_URL=postgres://${DB_USER}:${DB_PASSWORD}@${DB_URL}/${DB_DATABASE}
      - REDIS_URL=localhost:${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - KEY_FILE=${KEY_FILE}
      - DOMAIN=${DOMAIN}
      - CERT_CACHE=${API_CERT_CACHE}
      - GOMEMLIMIT=85MiB
    ports:
      - "${API_PORT}:${API_PORT}"
      - "80:80"
    volumes:
      - tls_cert:${API_CERT_CACHE}
    deploy:
      resources:
        limits:
            memory: 100m
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
            memory: 50m
  redis:
    image: redis:latest
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/root/redis
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=6379
      - REDIS_DATABASES=1
    command: redis-server /usr/local/etc/redis/redis.conf
    deploy:
      resources:
        limits:
            memory: 50m
volumes:
  db_data:
  redis_data:
  tls_cert:
